# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Pc998h2NFmlZB6zeQANXlbwrX3bO3sa
"""



"""
[판매 실적]
Q1. 'data_officesupplies' 데이터를 읽어오기
    # /content/drive/MyDrive/data/data_officesupplies.csv
Q2. Region을 West, Central, East로 구별하여 판매 수량(Units)을 다중 박스 플롯으로 출력하기
"""

import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

data2 = pd.read_csv("/content/drive/MyDrive/data/data_officesupplies.csv", encoding='cp949') # data_officesupplies 파일 읽어오기

boxplot = plt.figure()
axes1 = boxplot.add_subplot(1,1,1)

axes1.boxplot([data2[data2['Region']=='West']['Units'],
               data2[data2['Region']=='Central']['Units'],
               data2[data2['Region']== 'East']['Units']],
              labels = ['West', 'Central', 'East'])

axes1.set_xlabel('Region')
axes1.set_ylabel('Units')
axes1.set_title("Sales quantity by region")

plt.show()



